### PR TITLE
Ask to create unreleased changelog directory if it doesn't exist

### LINKED ISSUE #1: Ask to create default files if they don't exist
The tool fails gracefully with error messages in this scenario, but it'd be a nice QOL update to smoothen first-time setup

### PR DESCRIPTION
**Pull request by pg8wood**
Closes #1 and #3

To test manually: 
```sh
swift run changelog -d fakeDirectoryName add "hello, world"
```
...assuming you don't have a directory called `fakeDirectoryName` in your working directory 😉

### CODE REVIEW

File: Tests/changelog-generatorTests/LogCommandTests.swift [hunk 1]
```diff
@@ -7,22 +7,84 @@
...
-        XCTAssertThrowsError(try logCommand.run()) { error in
-            guard let changelogError = error as? ChangelogError,
-                  case .changelogDirectoryNotFound(_) = changelogError else {
-                XCTFail("Expected ChangelogError.changelogDirectoryNotFound to be thrown")
-                return
-            }
+        // This will swallow other errors thrown by the Log command, but these cases are handled by
+        // the rest of the test suite. In the future, String.write() should be wrapped and mocked
+        // in order to make this test better
+        try? logCommand.run()
```
Comment (pg8wood) [inline Tests/changelog-generatorTests/LogCommandTests.swift:33]: Fixed in #9!

**Review by mrketchup — APPROVED** [review]
👍 very nice 👍
